from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, Optional

from fastapi import FastAPI, HTTPException, Query, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.encoders import jsonable_encoder
from fastapi.responses import FileResponse, JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from livestorm_app.api_logic import (
    build_analysis_pdf,
    build_content_repurposing_pdf,
    build_smart_recap_pdf,
    fetch_available_events,
    fetch_all_session_data,
    fetch_session_base_data,
    fetch_session_transcript_data,
    fetch_event_sessions,
    format_service_error,
    get_cached_workspace,
    get_content_repurposing_job_data,
    get_deep_analysis_job_data,
    get_overall_analysis_job_data,
    get_smart_recap_job_data,
    get_transcript_job_status_data,
    list_workspace_sessions_data,
    save_speaker_labels,
    start_content_repurposing,
    start_deep_analysis,
    start_overall_analysis,
    start_smart_recap,
)
from livestorm_app.config import ENV_PATH, get_runtime_secret, load_env_file
from livestorm_app.db import ensure_database_schema, fetch_cover_image
from livestorm_app.oauth_client import (
    LIVESTORM_OAUTH_COOKIE,
    LIVESTORM_OAUTH_HANDSHAKE_COOKIE,
    build_authorization_url,
    delete_connection,
    exchange_authorization_code,
    fetch_me,
    get_connection_identity,
    get_frontend_app_url,
    oauth_enabled,
    persist_oauth_connection,
    refresh_connection_if_needed,
    seed_dev_connection,
    validate_handshake,
)


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

BASE_DIR = Path(__file__).resolve().parent
FRONTEND_DIST_DIR = BASE_DIR / "frontend" / "dist"
BRAND_ASSETS_DIR = BASE_DIR / "assets"


class EventSessionsRequest(BaseModel):
    api_key: str = Field("", alias="apiKey")
    event_id: str = Field(..., alias="eventId")


class WorkspaceEventsRequest(BaseModel):
    api_key: str = Field(..., alias="apiKey")
    page_number: int = Field(0, alias="pageNumber")
    page_size: int = Field(20, alias="pageSize")
    title: str = Field("", alias="title")
    scheduling_status: str = Field("", alias="schedulingStatus")


class FetchSessionRequest(BaseModel):
    api_key: str = Field("", alias="apiKey")
    transcript_api_key: Optional[str] = Field("", alias="transcriptApiKey")
    force_refresh: bool = Field(False, alias="forceRefresh")


class SpeakerLabelsRequest(BaseModel):
    api_key: str = Field("", alias="apiKey")
    speaker_names: Dict[str, str] = Field(default_factory=dict, alias="speakerNames")


class AnalysisRequest(BaseModel):
    api_key: str = Field("", alias="apiKey")
    output_language: str = Field("English", alias="outputLanguage")


class SmartRecapRequest(BaseModel):
    api_key: str = Field("", alias="apiKey")
    tone: str


def _raise_http_error(resource_label: str, exc: Exception, status_code: int = 400) -> None:
    error_payload = format_service_error(exc, resource_label)
    raise HTTPException(
        status_code=status_code,
        detail={
            "resource": resource_label,
            "message": error_payload["message"],
            "details": error_payload["details"],
        },
    )


def _resolve_organization_id(request: Request) -> str:
    """Resolve the requesting user's `organization_id` (or '' when unknown).

    Used to scope session_cache reads + initial upserts so teammates in
    the same Livestorm organization share cached results, but cross-org
    callers don't see them. When the user authenticated with the local
    LS_API_KEY fallback (no OAuth connection), this returns "" — those
    callers read the cache without an org filter, matching legacy
    behaviour for local development.
    """
    connection_id = str(request.cookies.get(LIVESTORM_OAUTH_COOKIE) or "").strip()
    if not connection_id:
        return ""
    connection = refresh_connection_if_needed(connection_id)
    if not isinstance(connection, dict):
        return ""
    return str(connection.get("organization_id") or "").strip()


def _resolve_generator_kwargs(request: Request) -> Dict[str, Any]:
    """Pull `{created_by_user_id, created_by_email, created_by_name}` from
    the OAuth connection.

    Empty dict when the caller is in LS_API_KEY-only mode (no OAuth
    connection) — the cache stores blanks then, and the "Generated by"
    UI falls back to "Unknown user". Only `created_by_name` falls back
    to the email when the profile has no full_name.
    """
    connection_id = str(request.cookies.get(LIVESTORM_OAUTH_COOKIE) or "").strip()
    if not connection_id:
        return {}
    connection = refresh_connection_if_needed(connection_id)
    if not isinstance(connection, dict):
        return {}
    profile = connection.get("profile") or {}
    profile = profile if isinstance(profile, dict) else {}
    user_id = str(connection.get("user_id") or profile.get("user_id") or "").strip()
    email = str(connection.get("email") or profile.get("email") or "").strip()
    name = str(profile.get("full_name") or "").strip() or email
    out: Dict[str, Any] = {}
    if user_id:
        out["created_by_user_id"] = user_id
    if email:
        out["created_by_email"] = email
    if name:
        out["created_by_name"] = name
    return out


def _resolve_livestorm_auth(raw_api_key: str, request: Request) -> str:
    direct_api_key = str(raw_api_key or "").strip()
    if direct_api_key:
        return direct_api_key
    if _allow_local_api_key_fallback(request):
        local_api_key = get_runtime_secret("LS_API_KEY", "")
        if str(local_api_key or "").strip():
            return str(local_api_key).strip()
    connection_id = str(request.cookies.get(LIVESTORM_OAUTH_COOKIE) or "").strip()
    if not connection_id:
        raise HTTPException(
            status_code=401,
            detail={"resource": "Livestorm authentication", "message": "Please connect with Livestorm first."},
        )
    connection = refresh_connection_if_needed(connection_id)
    if not isinstance(connection, dict):
        raise HTTPException(
            status_code=401,
            detail={"resource": "Livestorm authentication", "message": "Your Livestorm connection has expired. Please reconnect."},
        )
    access_token = str(connection.get("access_token") or "").strip()
    token_type = str(connection.get("token_type") or "Bearer").strip() or "Bearer"
    if not access_token:
        raise HTTPException(
            status_code=401,
            detail={"resource": "Livestorm authentication", "message": "Your Livestorm connection is missing an access token. Please reconnect."},
        )
    return f"{token_type} {access_token}"


def _get_bootstrap_auth(request: Request) -> Dict[str, Any]:
    connection_id = str(request.cookies.get(LIVESTORM_OAUTH_COOKIE) or "").strip()
    connection = refresh_connection_if_needed(connection_id) if connection_id else None
    return {
        "oauthEnabled": oauth_enabled(),
        "connectedUser": get_connection_identity(connection),
        "allowLocalApiKeyFallback": _allow_local_api_key_fallback(request),
    }


def _allow_local_api_key_fallback(request: Request | None) -> bool:
    if request is None:
        return False
    hostname = str(request.url.hostname or "").strip().lower()
    if hostname not in {"127.0.0.1", "localhost", "::1", "0.0.0.0"}:
        return False
    return bool(str(get_runtime_secret("LS_API_KEY", "") or "").strip())


load_env_file()
try:
    ensure_database_schema()
except Exception:
    logger.exception("Database schema initialization failed")

app = FastAPI(title="Livestorm Post Event Analysis API", version="0.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

if BRAND_ASSETS_DIR.exists():
    app.mount("/brand-assets", StaticFiles(directory=BRAND_ASSETS_DIR), name="brand-assets")


@app.get("/api/health")
def healthcheck() -> Dict[str, str]:
    return {"status": "ok"}


@app.get("/api/bootstrap")
def bootstrap_defaults(request: Request) -> Dict[str, Any]:
    auth = _get_bootstrap_auth(request)
    default_api_key = ""
    if ENV_PATH.exists() and (not auth.get("oauthEnabled") or auth.get("allowLocalApiKeyFallback")):
        default_api_key = get_runtime_secret("LS_API_KEY", "")
    return {
        "defaults": {
            "apiKey": default_api_key,
        },
        "auth": auth,
    }


@app.get("/api/auth/livestorm/start")
def start_livestorm_oauth(returnTo: str = Query("/")) -> Response:
    if not oauth_enabled():
        raise HTTPException(status_code=400, detail={"resource": "OAuth", "message": "Livestorm OAuth is not configured on the server yet."})
    auth_request = build_authorization_url(return_to=returnTo)
    response = RedirectResponse(auth_request["url"], status_code=302)
    response.set_cookie(
        LIVESTORM_OAUTH_HANDSHAKE_COOKIE,
        auth_request["handshake_token"],
        httponly=True,
        samesite="lax",
        secure=False,
        max_age=600,
        path="/",
    )
    return response


@app.get("/api/auth/livestorm/callback")
def complete_livestorm_oauth(code: str = Query(""), state: str = Query(""), request: Request = None) -> Response:
    handshake_cookie = str((request.cookies.get(LIVESTORM_OAUTH_HANDSHAKE_COOKIE) if request else "") or "").strip()
    frontend_base = get_frontend_app_url()
    success_redirect = f"{frontend_base}/auth/callback?auth=success" if frontend_base else "/auth/callback?auth=success"
    failure_redirect = f"{frontend_base}/auth/callback?auth=error" if frontend_base else "/auth/callback?auth=error"
    if not handshake_cookie or not code.strip():
        response = RedirectResponse(failure_redirect, status_code=302)
        response.delete_cookie(LIVESTORM_OAUTH_HANDSHAKE_COOKIE, path="/")
        return response
    try:
        handshake = validate_handshake(handshake_cookie, state)
        token_payload = exchange_authorization_code(code.strip(), str(handshake.get("verifier") or "").strip())
        me_payload = fetch_me(str(token_payload.get("access_token") or "").strip())
        connection = persist_oauth_connection(token_payload, me_payload)
        response = RedirectResponse(success_redirect, status_code=302)
        response.set_cookie(
            LIVESTORM_OAUTH_COOKIE,
            str(connection.get("connection_id") or "").strip(),
            httponly=True,
            samesite="lax",
            secure=False,
            max_age=60 * 60 * 24 * 30,
            path="/",
        )
        response.delete_cookie(LIVESTORM_OAUTH_HANDSHAKE_COOKIE, path="/")
        return response
    except Exception:
        logger.exception("Livestorm OAuth callback failed")
        response = RedirectResponse(failure_redirect, status_code=302)
        response.delete_cookie(LIVESTORM_OAUTH_HANDSHAKE_COOKIE, path="/")
        return response


@app.post("/api/auth/logout")
def logout_livestorm_oauth(request: Request) -> Response:
    connection_id = str(request.cookies.get(LIVESTORM_OAUTH_COOKIE) or "").strip()
    if connection_id:
        delete_connection(connection_id)
    response = JSONResponse({"ok": True})
    response.delete_cookie(LIVESTORM_OAUTH_COOKIE, path="/")
    return response


@app.get("/api/dev/auto-login")
def dev_auto_login(request: Request) -> Response:
    """Localhost-only: seed a real OAuth identity from LS_API_KEY.

    Calls /me with the local API key, stores the user/org identity in
    oauth_connections under a stable connection_id, and sets the session
    cookie — so org filtering, 'Generated by', and the session card list
    all behave as they would after a real OAuth login.
    """
    if not _allow_local_api_key_fallback(request):
        raise HTTPException(status_code=403, detail="Dev auto-login is only available on localhost with LS_API_KEY set.")
    api_key = str(get_runtime_secret("LS_API_KEY", "") or "").strip()
    try:
        connection_id = seed_dev_connection(api_key)
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Failed to fetch identity from Livestorm /me: {exc}") from exc
    response = RedirectResponse(url="/", status_code=302)
    response.set_cookie(key=LIVESTORM_OAUTH_COOKIE, value=connection_id, httponly=True, samesite="lax", path="/")
    return response


@app.get("/api/workspace-sessions")
def workspace_sessions(http_request: Request) -> Dict[str, Any]:
    """Phase 4: list every cached session the calling user's org can see.

    Powers the Single Analysis card grid. Filters by `organization_id`
    from the OAuth connection. Returns `{ sessions: [] }` when:
      - the caller has no OAuth connection (local LS_API_KEY mode)
      - the org has no cached sessions yet
    The frontend treats empty list as the empty-state for the page.
    """
    org_id = _resolve_organization_id(http_request)
    if not org_id:
        # No OAuth org → no workspace view to show. Return empty rather
        # than 401 so the page can render a "connect with Livestorm to
        # see your workspace sessions" CTA.
        return {"sessions": []}
    return list_workspace_sessions_data(org_id)


@app.post("/api/event-sessions")
def event_sessions(request: EventSessionsRequest, http_request: Request) -> Dict[str, Any]:
    try:
        api_key = _resolve_livestorm_auth(request.api_key, http_request)
        return fetch_event_sessions(api_key, request.event_id)
    except Exception as exc:
        _raise_http_error("Event sessions", exc)
        raise


@app.post("/api/workspace-events")
def workspace_events(request: WorkspaceEventsRequest, http_request: Request) -> Dict[str, Any]:
    try:
        api_key = _resolve_livestorm_auth(request.api_key, http_request)
        return fetch_available_events(
            api_key,
            page_number=request.page_number,
            page_size=request.page_size,
            title=request.title,
            scheduling_status=request.scheduling_status,
        )
    except Exception as exc:
        _raise_http_error("Workspace events", exc)
        raise


@app.get("/api/sessions/{session_id}/cover.png")
def get_session_cover_image(session_id: str, http_request: Request) -> Response:
    """Serve the OpenAI-generated cover image for the workspace card grid.

    BYTEA columns stay out of `/api/workspace-sessions` so that endpoint
    is small (no 50× 2 MB payloads). The card looks up `hasCoverImage`
    there and renders `<img src=".../cover.png">` only when true.

    Org-scoped via `_resolve_organization_id` — same access rule as
    everything else. Returns 404 with a small JSON body when the row
    has no cover yet (the frontend falls back to the placeholder
    gradient on a network error).
    """
    try:
        org_id = _resolve_organization_id(http_request)
        cover = fetch_cover_image(session_id, organization_id=org_id)
        if not isinstance(cover, dict) or not cover.get("bytes"):
            return JSONResponse({"message": "Cover image not available."}, status_code=404)
        # Cache aggressively in the browser — the bytes don't change
        # until the worker rewrites the row, and the URL itself isn't
        # versioned (yet). Once we regenerate, the user can hard-refresh.
        headers = {
            "Cache-Control": "public, max-age=86400",
            "Content-Type": cover.get("mime", "image/png"),
        }
        return Response(content=cover["bytes"], media_type=headers["Content-Type"], headers=headers)
    except Exception:
        logger.exception("Cover image route failed for session_id=%s", session_id)
        return JSONResponse({"message": "Cover image lookup failed."}, status_code=500)


@app.get("/api/sessions/{session_id}")
def get_session_workspace(session_id: str, http_request: Request) -> Dict[str, Any]:
    org_id = _resolve_organization_id(http_request)
    cached = get_cached_workspace(session_id, organization_id=org_id)
    if not isinstance(cached, dict):
        raise HTTPException(status_code=404, detail={"resource": "Session cache", "message": "No cached session found."})
    return cached


@app.get("/api/sessions/{session_id}/cached")
def get_cached_session_workspace(session_id: str, http_request: Request) -> Response:
    try:
        org_id = _resolve_organization_id(http_request)
        cached = get_cached_workspace(session_id, organization_id=org_id)
        if not isinstance(cached, dict):
            return Response(status_code=204)
        return JSONResponse(content=jsonable_encoder(cached))
    except Exception:
        logger.exception("Cached session route failed for session_id=%s", session_id)
        return Response(status_code=204)


@app.post("/api/sessions/{session_id}/fetch")
def fetch_session_workspace(session_id: str, request: FetchSessionRequest, http_request: Request) -> Dict[str, Any]:
    try:
        api_key = _resolve_livestorm_auth(request.api_key, http_request)
        org_id = _resolve_organization_id(http_request)
        generator = _resolve_generator_kwargs(http_request)
        transcript_api_key = str(request.transcript_api_key or "").strip() or get_runtime_secret("GLADIA_KEY", "")
        return fetch_all_session_data(
            api_key=api_key,
            transcript_api_key=transcript_api_key,
            session_id=session_id,
            force_refresh=request.force_refresh,
            organization_id=org_id,
            **generator,
        )
    except Exception as exc:
        _raise_http_error("Session data", exc)
        raise


@app.post("/api/sessions/{session_id}/fetch-base")
def fetch_session_base_workspace(session_id: str, request: FetchSessionRequest, http_request: Request) -> Dict[str, Any]:
    try:
        api_key = _resolve_livestorm_auth(request.api_key, http_request)
        org_id = _resolve_organization_id(http_request)
        generator = _resolve_generator_kwargs(http_request)
        return fetch_session_base_data(
            api_key=api_key,
            session_id=session_id,
            force_refresh=request.force_refresh,
            organization_id=org_id,
            **generator,
        )
    except Exception as exc:
        _raise_http_error("Session overview", exc)
        raise


@app.post("/api/sessions/{session_id}/fetch-transcript")
def fetch_session_transcript_workspace(session_id: str, request: FetchSessionRequest, http_request: Request) -> Dict[str, Any]:
    try:
        api_key = _resolve_livestorm_auth(request.api_key, http_request)
        org_id = _resolve_organization_id(http_request)
        generator = _resolve_generator_kwargs(http_request)
        transcript_api_key = str(request.transcript_api_key or "").strip() or get_runtime_secret("GLADIA_KEY", "")
        return fetch_session_transcript_data(
            api_key=api_key,
            transcript_api_key=transcript_api_key,
            session_id=session_id,
            force_refresh=request.force_refresh,
            organization_id=org_id,
            **generator,
        )
    except Exception as exc:
        _raise_http_error("Transcript", exc)
        raise


@app.get("/api/sessions/{session_id}/transcript-job")
def get_transcript_job_status(session_id: str, http_request: Request) -> Dict[str, Any]:
    try:
        api_key = _resolve_livestorm_auth("", http_request)
        org_id = _resolve_organization_id(http_request)
        return get_transcript_job_status_data(api_key, session_id, organization_id=org_id)
    except Exception as exc:
        _raise_http_error("Transcript job", exc)
        raise


@app.post("/api/sessions/{session_id}/speaker-labels")
def update_speaker_labels(session_id: str, request: SpeakerLabelsRequest, http_request: Request) -> Dict[str, Any]:
    try:
        api_key = _resolve_livestorm_auth(request.api_key, http_request)
        org_id = _resolve_organization_id(http_request)
        return save_speaker_labels(api_key, session_id, request.speaker_names, organization_id=org_id)
    except Exception as exc:
        _raise_http_error("Speaker labels", exc)
        raise


@app.post("/api/sessions/{session_id}/analysis")
def overall_analysis(session_id: str, request: AnalysisRequest, http_request: Request) -> Dict[str, Any]:
    """Start an Overall Analysis job.

    Phase 2 contract change: this no longer returns the analysis body
    inline. Returns either the full serialised workspace (if already
    cached for the requested language) or { jobId, jobKind, jobStatus,
    language } so the frontend can poll `/analysis/job`.
    """
    try:
        org_id = _resolve_organization_id(http_request)
        return start_overall_analysis(session_id, request.output_language, organization_id=org_id)
    except Exception as exc:
        _raise_http_error("Analysis", exc)
        raise


@app.get("/api/sessions/{session_id}/analysis/job")
def overall_analysis_job(session_id: str, http_request: Request, jobId: str = Query(""), language: str = Query("English")) -> Dict[str, Any]:
    try:
        org_id = _resolve_organization_id(http_request)
        return get_overall_analysis_job_data(session_id, jobId, language, organization_id=org_id)
    except Exception as exc:
        _raise_http_error("Analysis", exc)
        raise


@app.post("/api/sessions/{session_id}/deep-analysis")
def deep_analysis(session_id: str, request: AnalysisRequest, http_request: Request) -> Dict[str, Any]:
    """Start a Deep Analysis job. See `overall_analysis` for the contract."""
    try:
        org_id = _resolve_organization_id(http_request)
        return start_deep_analysis(session_id, request.output_language, organization_id=org_id)
    except Exception as exc:
        _raise_http_error("Deep analysis", exc)
        raise


@app.get("/api/sessions/{session_id}/deep-analysis/job")
def deep_analysis_job(session_id: str, http_request: Request, jobId: str = Query(""), language: str = Query("English")) -> Dict[str, Any]:
    try:
        org_id = _resolve_organization_id(http_request)
        return get_deep_analysis_job_data(session_id, jobId, language, organization_id=org_id)
    except Exception as exc:
        _raise_http_error("Deep analysis", exc)
        raise


@app.get("/api/sessions/{session_id}/analysis-pdf")
def analysis_pdf(session_id: str, kind: str = Query(...), language: str = Query("English")) -> Response:
    try:
        result = build_analysis_pdf(session_id, kind, language)
        filename = str(result["filename"])
        pdf_bytes = result["content"]
        headers = {"Content-Disposition": f'attachment; filename="{filename}"'}
        return Response(content=pdf_bytes, media_type="application/pdf", headers=headers)
    except Exception as exc:
        _raise_http_error("Analysis PDF", exc)
        raise


@app.post("/api/sessions/{session_id}/smart-recap")
def smart_recap(session_id: str, request: SmartRecapRequest, http_request: Request) -> Dict[str, Any]:
    """Start a Smart Recap job. Same contract as overall_analysis, keyed by tone."""
    try:
        org_id = _resolve_organization_id(http_request)
        return start_smart_recap(session_id, request.tone, organization_id=org_id)
    except Exception as exc:
        _raise_http_error("Smart Recap", exc)
        raise


@app.get("/api/sessions/{session_id}/smart-recap/job")
def smart_recap_job(session_id: str, http_request: Request, jobId: str = Query(""), tone: str = Query("professional")) -> Dict[str, Any]:
    try:
        org_id = _resolve_organization_id(http_request)
        return get_smart_recap_job_data(session_id, jobId, tone, organization_id=org_id)
    except Exception as exc:
        _raise_http_error("Smart Recap", exc)
        raise


@app.get("/api/sessions/{session_id}/smart-recap-pdf")
def smart_recap_pdf(session_id: str, tone: str = Query(...)) -> Response:
    try:
        result = build_smart_recap_pdf(session_id, tone)
        filename = str(result["filename"])
        pdf_bytes = result["content"]
        headers = {"Content-Disposition": f'attachment; filename="{filename}"'}
        return Response(content=pdf_bytes, media_type="application/pdf", headers=headers)
    except Exception as exc:
        _raise_http_error("Smart Recap PDF", exc)
        raise


@app.post("/api/sessions/{session_id}/content-repurposing")
def content_repurposing(session_id: str, request: AnalysisRequest, http_request: Request) -> Dict[str, Any]:
    """Start a Content Repurposing job. Same contract as overall_analysis."""
    try:
        org_id = _resolve_organization_id(http_request)
        return start_content_repurposing(session_id, request.output_language, organization_id=org_id)
    except Exception as exc:
        _raise_http_error("Content Repurposing", exc)
        raise


@app.get("/api/sessions/{session_id}/content-repurposing/job")
def content_repurposing_job(session_id: str, http_request: Request, jobId: str = Query(""), language: str = Query("English")) -> Dict[str, Any]:
    try:
        org_id = _resolve_organization_id(http_request)
        return get_content_repurposing_job_data(session_id, jobId, language, organization_id=org_id)
    except Exception as exc:
        _raise_http_error("Content Repurposing", exc)
        raise


@app.get("/api/sessions/{session_id}/content-repurposing-pdf")
def content_repurposing_pdf(session_id: str, language: str = Query("English"), item: str = Query(...)) -> Response:
    try:
        result = build_content_repurposing_pdf(session_id, language, item)
        filename = str(result["filename"])
        pdf_bytes = result["content"]
        headers = {"Content-Disposition": f'attachment; filename="{filename}"'}
        return Response(content=pdf_bytes, media_type="application/pdf", headers=headers)
    except Exception as exc:
        _raise_http_error("Content Repurposing PDF", exc)
        raise


if FRONTEND_DIST_DIR.exists():
    assets_dir = FRONTEND_DIST_DIR / "assets"
    if assets_dir.exists():
        app.mount("/assets", StaticFiles(directory=assets_dir), name="assets")

    # Vite ships hashed asset filenames (index-abc123.js) but the
    # HTML that references them is unhashed and SHOULD NEVER be cached.
    # Without these headers, a Render deploy that ships a fresh hash
    # leaves users with browsers/CDNs holding the OLD index.html
    # pointing at the OLD asset — the new asset 404s because the old
    # file no longer exists in /assets. Forcing no-cache on the HTML
    # entry-point makes every navigation re-fetch the index, while
    # asset files are still served fresh by the StaticFiles mount above
    # (the hashed filenames make them inherently cache-safe — a
    # different bundle has a different URL).
    _INDEX_HTML_HEADERS = {
        "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
        "Pragma": "no-cache",
        "Expires": "0",
    }

    @app.get("/{full_path:path}")
    def serve_frontend(full_path: str) -> Any:
        requested_path = FRONTEND_DIST_DIR / full_path
        if full_path and requested_path.exists() and requested_path.is_file():
            return FileResponse(requested_path)
        index_path = FRONTEND_DIST_DIR / "index.html"
        if index_path.exists():
            return FileResponse(index_path, headers=_INDEX_HTML_HEADERS)
        return JSONResponse({"message": "Frontend build not found."}, status_code=404)
