<script setup>
import { computed } from "vue";
import { useWorkspace } from "../store/workspace";

// Hero header for every per-session route under /single-analysis/:id/*.
// Echoes the cover image the user clicked on the grid (or the
// gradient placeholder when no cover exists yet), then a tight
// title + meta block below.
//
// Reads everything from `state.workspace.meta` (added in
// _serialize_cached_session). Renders nothing when the workspace
// hasn't loaded yet — the page's existing loader handles that frame.

const { state } = useWorkspace();

const workspace = computed(() => state.workspace);
const sessionId = computed(() => String(state.workspace?.sessionId || "").trim());
const meta = computed(() => state.workspace?.meta || {});

// Don't render the hero until we have something meaningful — avoids
// a tall empty banner above the loading spinner.
const isReady = computed(
  () => Boolean(sessionId.value && (meta.value?.eventTitle || meta.value?.sessionName)),
);

const eventTitle = computed(
  () => String(meta.value?.eventTitle || "").trim() || String(meta.value?.sessionName || "").trim() || "Untitled session",
);

const metaLine = computed(() => {
  const parts = [];
  const startedAt = String(meta.value?.startedAtLabel || "").trim();
  if (startedAt) parts.push(startedAt);
  const duration = String(meta.value?.durationLabel || "").trim();
  if (duration) parts.push(duration);
  const attendees = meta.value?.attendeesCount;
  if (typeof attendees === "number" && attendees >= 0) {
    parts.push(`${attendees} attendees`);
  }
  return parts.join(" · ");
});

const generatorLine = computed(() => {
  const who =
    String(meta.value?.generatedByName || "").trim() ||
    String(meta.value?.generatedByEmail || "").trim();
  const when = String(meta.value?.generatedAtLabel || "").trim();
  if (!who && !when) return "";
  if (who && when) return `Generated by ${who} · ${when}`;
  return who ? `Generated by ${who}` : `Generated · ${when}`;
});

// Same hash-based gradient placeholder the grid uses so the hero
// stays visually coherent with its card while waiting for the cover.
function hashString(input) {
  const text = String(input || "");
  let hash = 0;
  for (let i = 0; i < text.length; i += 1) {
    hash = (hash * 31 + text.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

const gradient = computed(() => {
  const hash = hashString(sessionId.value);
  const hueA = hash % 360;
  const hueB = (hash * 7 + 60) % 360;
  return `linear-gradient(135deg, hsl(${hueA}, 62%, 48%) 0%, hsl(${hueB}, 58%, 38%) 100%)`;
});

const coverImageUrl = computed(() => {
  if (!meta.value?.hasCoverImage || !sessionId.value) return "";
  const version = String(meta.value?.coverImageGeneratedAt || "").trim();
  const query = version ? `?v=${encodeURIComponent(version)}` : "";
  return `/api/sessions/${sessionId.value}/cover.png${query}`;
});

const initialsForCover = computed(() => {
  const label = String(eventTitle.value || "").trim();
  if (!label) return "—";
  const words = label.split(/\s+/).slice(0, 2);
  return words.map((w) => w[0]).join("").toUpperCase();
});
</script>

<template>
  <header v-if="isReady" class="session-hero">
    <div class="session-hero-cover" :style="{ background: gradient }">
      <img
        v-if="meta.hasCoverImage"
        class="session-hero-cover-image"
        :src="coverImageUrl"
        :alt="`Cover for ${eventTitle}`"
        loading="lazy"
      />
      <span v-else class="session-hero-cover-initials" aria-hidden="true">{{ initialsForCover }}</span>
    </div>
    <div class="session-hero-body">
      <h1 class="session-hero-title">{{ eventTitle }}</h1>
      <p v-if="metaLine" class="session-hero-meta">{{ metaLine }}</p>
      <p v-if="generatorLine" class="session-hero-generator">{{ generatorLine }}</p>
    </div>
  </header>
</template>

<style scoped>
.session-hero {
  /* The hero sits at the top of every session-detail tab. Composition:
     a wide cover panel on the left, a tight title/meta column on the
     right. The whole header is wrapped in the same dark surface +
     border tokens used by the rest of the page so it feels like a
     first-class section, not a banner glued on top. */
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1.2fr);
  gap: 20px;
  align-items: stretch;
  background: var(--color-surface-neutral-alpha-100);
  border: 1px solid var(--color-borders-neutral-light);
  border-radius: var(--spacing-rounded-lg);
  padding: 16px;
  margin-bottom: 20px;
}

@media (max-width: 880px) {
  .session-hero {
    grid-template-columns: 1fr;
  }
}

.session-hero-cover {
  aspect-ratio: 3 / 2;
  border-radius: 10px;
  overflow: hidden;
  display: grid;
  place-items: center;
}

.session-hero-cover-image {
  width: 100%;
  height: 100%;
  object-fit: contain;
  display: block;
}

.session-hero-cover-initials {
  font-size: 56px;
  font-weight: 600;
  color: rgba(255, 255, 255, 0.92);
  letter-spacing: 0.02em;
}

.session-hero-body {
  display: flex;
  flex-direction: column;
  justify-content: center;
  gap: 10px;
  min-width: 0;
}

.session-hero-title {
  /* Editorial-feel headline. Sized larger than the per-tab <h2> so
     the hero clearly anchors the page, but capped via line-clamp so
     a very long event title doesn't break the layout. */
  font-size: 28px;
  font-weight: 600;
  line-height: 1.2;
  margin: 0;
  color: var(--color-text-neutral-base);
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.session-hero-meta {
  font-size: 14px;
  color: var(--color-text-neutral-secondary);
  margin: 0;
}

.session-hero-generator {
  font-size: 12px;
  color: var(--color-text-neutral-tertiary);
  font-style: italic;
  margin: 0;
}
</style>
