<script setup>
import { computed, onMounted, ref, watch } from "vue";
import { useRouter } from "vue-router";
import { useWorkspace } from "../store/workspace";

const { state, loadWorkspaceSessions } = useWorkspace();
const router = useRouter();

function maybeLoad() {
  // Only fire when we actually have an auth context. Without it,
  // loadWorkspaceSessions short-circuits to an empty list without
  // touching the server, and we'd never re-trigger when auth lands.
  if (!state.auth.connectedUser && !state.auth.allowLocalApiKeyFallback) {
    return;
  }
  if (!state.workspaceSessions.length || isStale.value) {
    loadWorkspaceSessions().catch(() => {});
  }
}

onMounted(maybeLoad);

watch(
  () => [state.auth.connectedUser, state.auth.allowLocalApiKeyFallback],
  () => maybeLoad(),
);

const STALE_AFTER_MS = 60 * 1000;
const isStale = computed(
  () => Date.now() - (state.workspaceSessionsLoadedAt || 0) > STALE_AFTER_MS,
);

const isLoadingFirstTime = computed(
  () => state.loading.workspaceSessions && !state.workspaceSessions.length,
);

const sessions = computed(() => state.workspaceSessions || []);
const hasAnySessions = computed(() => sessions.value.length > 0);
const isConnected = computed(
  () => Boolean(state.auth?.connectedUser || state.auth?.allowLocalApiKeyFallback),
);

// ── View mode (grid / list), persisted in localStorage ─────────────────────
const VIEW_MODE_STORAGE_KEY = "stormiq:single-analysis:viewMode";
const viewMode = ref(loadViewMode());

function loadViewMode() {
  try {
    const value = String(window.localStorage.getItem(VIEW_MODE_STORAGE_KEY) || "").trim();
    return value === "list" ? "list" : "grid";
  } catch (_) {
    return "grid";
  }
}

watch(viewMode, (next) => {
  try {
    window.localStorage.setItem(VIEW_MODE_STORAGE_KEY, next);
  } catch (_) {
    // Ignore localStorage failures (private browsing, etc.) — the
    // chosen mode is still honoured for the rest of the session.
  }
});

// ── Search / filter / sort state ───────────────────────────────────────────
const searchQuery = ref("");
const eventFilter = ref(""); // "" = all events; otherwise an event_id
const sortBy = ref("generatedDesc"); // see SORT_OPTIONS below

const SORT_OPTIONS = [
  { value: "generatedDesc", label: "Newest (added)" },
  { value: "generatedAsc", label: "Oldest (added)" },
  { value: "sessionDateDesc", label: "Session date (newest first)" },
  { value: "sessionDateAsc", label: "Session date (oldest first)" },
  { value: "eventAsc", label: "Event title (A→Z)" },
  { value: "eventDesc", label: "Event title (Z→A)" },
  { value: "generatorAsc", label: "Generated by (A→Z)" },
];

// Filter dropdown options. Group every session by event_id (skipping
// rows with no event_id), label "Event title (N sessions)", sort by
// session count desc so the busy events surface first.
const eventOptions = computed(() => {
  const groups = new Map();
  for (const session of sessions.value) {
    const eventId = String(session.eventId || "").trim();
    if (!eventId) continue;
    const existing = groups.get(eventId);
    if (existing) {
      existing.count += 1;
    } else {
      groups.set(eventId, {
        value: eventId,
        title: String(session.eventTitle || "").trim() || "Untitled event",
        count: 1,
      });
    }
  }
  return Array.from(groups.values())
    .sort((a, b) => b.count - a.count || a.title.localeCompare(b.title))
    .map((group) => ({
      value: group.value,
      label: `${group.title} (${group.count})`,
    }));
});

const displayedSessions = computed(() => {
  const query = searchQuery.value.trim().toLowerCase();
  const filter = eventFilter.value;

  let list = sessions.value.slice();

  if (filter) {
    list = list.filter((card) => String(card.eventId || "") === filter);
  }

  if (query) {
    list = list.filter((card) => {
      const haystack = [
        card.eventTitle,
        card.sessionName,
        card.generatedByName,
        card.generatedByEmail,
      ]
        .map((value) => String(value || "").toLowerCase())
        .join(" ");
      return haystack.includes(query);
    });
  }

  list.sort((a, b) => compareSessions(a, b, sortBy.value));
  return list;
});

function compareSessions(a, b, mode) {
  const safeStr = (v) => String(v || "");
  const safeIso = (v) => new Date(String(v || "")).getTime() || 0;
  const safeUnix = (v) => Number(v) || 0;
  switch (mode) {
    case "generatedAsc":
      return safeIso(a.generatedAtIso) - safeIso(b.generatedAtIso);
    case "sessionDateDesc":
      return safeUnix(b.startedAtUnix) - safeUnix(a.startedAtUnix);
    case "sessionDateAsc":
      return safeUnix(a.startedAtUnix) - safeUnix(b.startedAtUnix);
    case "eventAsc":
      return safeStr(a.eventTitle).localeCompare(safeStr(b.eventTitle));
    case "eventDesc":
      return safeStr(b.eventTitle).localeCompare(safeStr(a.eventTitle));
    case "generatorAsc":
      return safeStr(a.generatedByName || a.generatedByEmail).localeCompare(
        safeStr(b.generatedByName || b.generatedByEmail),
      );
    case "generatedDesc":
    default:
      return safeIso(b.generatedAtIso) - safeIso(a.generatedAtIso);
  }
}

// ── Card helpers ───────────────────────────────────────────────────────────
function hashString(input) {
  const text = String(input || "");
  let hash = 0;
  for (let i = 0; i < text.length; i += 1) {
    hash = (hash * 31 + text.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

function gradientFor(sessionId) {
  const hash = hashString(sessionId);
  const hueA = hash % 360;
  const hueB = (hash * 7 + 60) % 360;
  return `linear-gradient(135deg, hsl(${hueA}, 62%, 48%) 0%, hsl(${hueB}, 58%, 38%) 100%)`;
}

function coverImageUrl(card) {
  // Phase 4: real AI cover, generated from the Professional Smart
  // Recap. Falls back to the gradient placeholder when the row
  // doesn't have one yet (legacy rows + brand-new fetches whose
  // cover job hasn't completed). Adds a `?v=<iso>` cache-buster only
  // when we have a generated_at timestamp so subsequent regenerations
  // bypass the browser's max-age=86400 cache for this URL.
  if (!card?.hasCoverImage || !card?.sessionId) return "";
  return `/api/sessions/${card.sessionId}/cover.png`;
}

function initialsFor(label) {
  const cleaned = String(label || "").trim();
  if (!cleaned) return "—";
  const words = cleaned.split(/\s+/).slice(0, 2);
  return words.map((w) => w[0]).join("").toUpperCase();
}

function cardTitle(card) {
  // Phase 4 follow-up: prefer the event title. Sessions rarely have
  // their own name set — the user-meaningful label is the event the
  // session belongs to.
  return (
    String(card.eventTitle || "").trim() ||
    String(card.sessionName || "").trim() ||
    "Untitled session"
  );
}

function formattedDate(card) {
  return card.startedAtLabel || "—";
}

function generatedByLine(card) {
  const who =
    String(card.generatedByName || "").trim() ||
    String(card.generatedByEmail || "").trim() ||
    "Unknown user";
  const when = String(card.generatedAtLabel || "").trim();
  return when ? `Generated by ${who} · ${when}` : `Generated by ${who}`;
}

function openSession(sessionId) {
  router.push(`/single-analysis/${sessionId}/session-overview`);
}

async function refresh() {
  await loadWorkspaceSessions().catch(() => {});
}

const showEmptyAfterFilters = computed(
  () => hasAnySessions.value && displayedSessions.value.length === 0,
);

function clearFilters() {
  searchQuery.value = "";
  eventFilter.value = "";
}
</script>

<template>
  <section class="page-section">
    <header class="single-analysis-header">
      <div>
        <h2>Single Analysis</h2>
        <p class="page-description">
          Sessions your workspace has already fetched. Click a card to open it.
        </p>
      </div>
      <button
        type="button"
        class="ghost-link-button"
        :disabled="state.loading.workspaceSessions"
        @click="refresh"
      >
        {{ state.loading.workspaceSessions ? "Refreshing…" : "Refresh" }}
      </button>
    </header>

    <section v-if="isLoadingFirstTime" class="panel loading-panel">
      <div class="loading-indicator" aria-hidden="true"></div>
      <div>
        <h3 class="loading-title">Loading workspace sessions</h3>
        <p class="loading-copy">Fetching the sessions teammates have already analysed.</p>
      </div>
    </section>

    <section v-else-if="!hasAnySessions && !isConnected" class="panel helper-panel">
      <h3>Connect with Livestorm to see your workspace</h3>
      <p>Once you're connected, every session your teammates fetch will appear here.</p>
    </section>

    <section v-else-if="!hasAnySessions" class="panel helper-panel">
      <h3>No sessions yet</h3>
      <p>
        Use <RouterLink class="ghost-link-button" to="/search">Search</RouterLink>
        to fetch your first session by ID, by event, or by browsing your workspace events.
      </p>
    </section>

    <template v-else>
      <!-- Controls: view mode toggle, search, event filter, sort. -->
      <div class="single-analysis-controls">
        <div class="single-analysis-controls-row">
          <input
            v-model="searchQuery"
            type="text"
            class="single-analysis-search"
            placeholder="Search by event, session, or generator…"
            aria-label="Search sessions"
          />
          <select v-model="eventFilter" aria-label="Filter by event" class="single-analysis-select">
            <option value="">All events ({{ sessions.length }})</option>
            <option v-for="option in eventOptions" :key="option.value" :value="option.value">
              {{ option.label }}
            </option>
          </select>
          <select v-model="sortBy" aria-label="Sort sessions" class="single-analysis-select">
            <option v-for="option in SORT_OPTIONS" :key="option.value" :value="option.value">
              Sort: {{ option.label }}
            </option>
          </select>
          <div class="single-analysis-viewmode" role="group" aria-label="View mode">
            <button
              type="button"
              class="single-analysis-viewmode-button"
              :class="{ active: viewMode === 'grid' }"
              :aria-pressed="viewMode === 'grid'"
              title="Grid view"
              @click="viewMode = 'grid'"
            >
              <span aria-hidden="true">▦</span>
              <span class="single-analysis-viewmode-label">Grid</span>
            </button>
            <button
              type="button"
              class="single-analysis-viewmode-button"
              :class="{ active: viewMode === 'list' }"
              :aria-pressed="viewMode === 'list'"
              title="List view"
              @click="viewMode = 'list'"
            >
              <span aria-hidden="true">≡</span>
              <span class="single-analysis-viewmode-label">List</span>
            </button>
          </div>
        </div>

        <div v-if="displayedSessions.length !== sessions.length" class="single-analysis-controls-meta">
          Showing {{ displayedSessions.length }} of {{ sessions.length }} session{{ sessions.length === 1 ? "" : "s" }}
          <button v-if="searchQuery || eventFilter" type="button" class="ghost-link-button" @click="clearFilters">
            Clear filters
          </button>
        </div>
      </div>

      <section v-if="showEmptyAfterFilters" class="panel helper-panel">
        <h3>No sessions match your filters</h3>
        <p>
          Try a different search term or
          <button type="button" class="ghost-link-button" @click="clearFilters">clear the filters</button>.
        </p>
      </section>

      <!-- Grid view: current card layout. -->
      <div v-else-if="viewMode === 'grid'" class="single-analysis-grid">
        <article
          v-for="card in displayedSessions"
          :key="card.sessionId"
          class="single-analysis-card"
          tabindex="0"
          role="button"
          :aria-label="`Open ${cardTitle(card)}`"
          @click="openSession(card.sessionId)"
          @keydown.enter="openSession(card.sessionId)"
          @keydown.space.prevent="openSession(card.sessionId)"
        >
          <div class="single-analysis-card-cover" :style="{ background: gradientFor(card.sessionId) }">
            <img
              v-if="card.hasCoverImage"
              class="single-analysis-card-cover-image"
              :src="coverImageUrl(card)"
              :alt="`Cover image for ${cardTitle(card)}`"
              loading="lazy"
            />
            <span v-else class="single-analysis-card-initials">{{ initialsFor(cardTitle(card)) }}</span>
          </div>
          <div class="single-analysis-card-body">
            <h3 class="single-analysis-card-title">{{ cardTitle(card) }}</h3>
            <p class="single-analysis-card-meta">
              <span>{{ formattedDate(card) }}</span>
              <span v-if="card.durationLabel"> · {{ card.durationLabel }}</span>
              <span v-if="card.attendeesCount != null"> · {{ card.attendeesCount }} attendees</span>
            </p>
            <p class="single-analysis-card-generator">{{ generatedByLine(card) }}</p>
          </div>
        </article>
      </div>

      <!-- List view: horizontal rows, denser. -->
      <div v-else class="single-analysis-list">
        <article
          v-for="card in displayedSessions"
          :key="card.sessionId"
          class="single-analysis-row"
          tabindex="0"
          role="button"
          :aria-label="`Open ${cardTitle(card)}`"
          @click="openSession(card.sessionId)"
          @keydown.enter="openSession(card.sessionId)"
          @keydown.space.prevent="openSession(card.sessionId)"
        >
          <div class="single-analysis-row-cover" :style="{ background: gradientFor(card.sessionId) }">
            <img
              v-if="card.hasCoverImage"
              class="single-analysis-row-cover-image"
              :src="coverImageUrl(card)"
              :alt="`Cover image for ${cardTitle(card)}`"
              loading="lazy"
            />
            <span v-else class="single-analysis-row-initials">{{ initialsFor(cardTitle(card)) }}</span>
          </div>
          <div class="single-analysis-row-body">
            <h3 class="single-analysis-row-title">{{ cardTitle(card) }}</h3>
            <p class="single-analysis-row-meta">
              <span>{{ formattedDate(card) }}</span>
              <span v-if="card.durationLabel"> · {{ card.durationLabel }}</span>
              <span v-if="card.attendeesCount != null"> · {{ card.attendeesCount }} attendees</span>
              <span class="single-analysis-row-generator"> · {{ generatedByLine(card) }}</span>
            </p>
          </div>
        </article>
      </div>
    </template>
  </section>
</template>

<style scoped>
.single-analysis-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
  gap: 16px;
  margin-bottom: 16px;
}

/* ── Controls bar ───────────────────────────────────────────────── */
.single-analysis-controls {
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-bottom: 16px;
}

.single-analysis-controls-row {
  display: grid;
  grid-template-columns: minmax(220px, 1fr) auto auto auto;
  gap: 8px;
  align-items: center;
}

@media (max-width: 880px) {
  .single-analysis-controls-row {
    grid-template-columns: 1fr 1fr;
  }
}

.single-analysis-search {
  min-width: 0;
}

.single-analysis-select {
  min-width: 0;
}

.single-analysis-viewmode {
  display: flex;
  gap: 0;
  border: 1px solid #c8d3da; /* nimbus-200 */
  border-radius: 8px;
  overflow: hidden;
  background: #ffffff;
}

.single-analysis-viewmode-button {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 8px 12px;
  background: transparent;
  border: 0;
  cursor: pointer;
  font-size: 13px;
  color: #4d5b66; /* grey-600 */
}

.single-analysis-viewmode-button + .single-analysis-viewmode-button {
  border-left: 1px solid #eaeef1; /* nimbus-100 */
}

.single-analysis-viewmode-button.active {
  background: #f0f4ff; /* blue-50 */
  color: #0b42c3;     /* brand-blue */
  font-weight: 600;
}

.single-analysis-viewmode-label {
  /* Hide label on narrow screens; keep icon. */
}
@media (max-width: 720px) {
  .single-analysis-viewmode-label { display: none; }
}

.single-analysis-controls-meta {
  display: flex;
  align-items: center;
  gap: 12px;
  font-size: 13px;
  color: #5d6d79; /* grey-500 */
}

/* ── Grid view (existing) ───────────────────────────────────────── */
.single-analysis-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 16px;
}

.single-analysis-card {
  background: #ffffff;
  border: 1px solid #eaeef1;
  border-radius: 12px;
  overflow: hidden;
  cursor: pointer;
  display: flex;
  flex-direction: column;
  transition: transform 120ms ease-out, box-shadow 120ms ease-out, border-color 120ms ease-out;
}

.single-analysis-card:hover,
.single-analysis-card:focus-visible {
  transform: translateY(-2px);
  box-shadow: 0 6px 16px rgba(11, 66, 195, 0.08);
  border-color: #b3cafe;
  outline: none;
}

.single-analysis-card-cover {
  aspect-ratio: 16 / 9;
  display: grid;
  place-items: center;
  overflow: hidden;
}

.single-analysis-card-cover-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.single-analysis-card-initials {
  font-size: 36px;
  font-weight: 600;
  color: rgba(255, 255, 255, 0.92);
  letter-spacing: 0.02em;
}

.single-analysis-card-body {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding: 14px 16px 16px;
}

.single-analysis-card-title {
  font-size: 16px;
  font-weight: 600;
  margin: 0;
  color: #232b2f;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.single-analysis-card-meta {
  font-size: 13px;
  color: #5d6d79;
  margin: 0;
}

.single-analysis-card-generator {
  font-size: 12px;
  color: #8094a3;
  margin: 4px 0 0;
  font-style: italic;
}

/* ── List view ──────────────────────────────────────────────────── */
.single-analysis-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.single-analysis-row {
  display: grid;
  grid-template-columns: 88px 1fr;
  gap: 14px;
  align-items: center;
  background: #ffffff;
  border: 1px solid #eaeef1;
  border-radius: 10px;
  padding: 8px 14px 8px 8px;
  cursor: pointer;
  transition: border-color 120ms ease-out, box-shadow 120ms ease-out;
}

.single-analysis-row:hover,
.single-analysis-row:focus-visible {
  border-color: #b3cafe;
  box-shadow: 0 4px 10px rgba(11, 66, 195, 0.06);
  outline: none;
}

.single-analysis-row-cover {
  aspect-ratio: 16 / 9;
  border-radius: 6px;
  display: grid;
  place-items: center;
  overflow: hidden;
}

.single-analysis-row-cover-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.single-analysis-row-initials {
  font-size: 18px;
  font-weight: 600;
  color: rgba(255, 255, 255, 0.92);
}

.single-analysis-row-body {
  display: flex;
  flex-direction: column;
  gap: 2px;
  min-width: 0;
}

.single-analysis-row-title {
  font-size: 15px;
  font-weight: 600;
  margin: 0;
  color: #232b2f;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.single-analysis-row-meta {
  font-size: 13px;
  color: #5d6d79;
  margin: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.single-analysis-row-generator {
  font-style: italic;
  color: #8094a3;
}
</style>
